local apps <const> = {
  ["Alacritty"] = ":alacritty:",
  ["Alfred Preferences"] = ":alfred:",
  ["Android Messages"] = ":android_messages:",
  ["Android Studio"] = ":android_studio:",
  ["App Store"] = ":app_store:",
  ["Audacity"] = ":audacity:",
  ["Bitwarden"] = ":bit_warden:",
  ["Blender"] = ":blender:",
  ["Calibre"] = ":book:",
  ["Brave Browser"] = ":brave_browser:",
  ["Calculator"] = ":calculator:",
  ["Calendar"] = ":calendar:",
  ["Code"] = ":code:",
  ["Code - Insiders"] = ":code:",
  ["Default"] = ":default:",
  ["Discord"] = ":discord:",
  ["Docker"] = ":docker:",
  ["Docker Desktop"] = ":docker:",
  ["Emacs"] = ":emacs:",
  ["FaceTime"] = ":face_time:",
  ["Finder"] = ":finder:",
  ["Firefox"] = ":firefox:",
  ["System Preferences"] = ":gear:",
  ["System Settings"] = ":gear:",
  ["GitHub Desktop"] = ":git_hub:",
  ["Google Chrome"] = ":google_chrome:",
  ["iTerm"] = ":iterm:",
  ["iTerm2"] = ":iterm:",
  ["Secrets"] = ":one_password:",
  ["Keynote"] = ":keynote:",
  ["kitty"] = ":kitty:",
  ["Mail"] = ":mail:",
  ["Maps"] = ":maps:",
  ["Ghostty"] = ":ghostty:",
  ["Google Maps"] = ":maps:",
  ["Google Chat"] = ":android_messages:",
  ["Google Meet"] = ":camera:",
  ["Matlab"] = ":matlab:",
  ["Messages"] = ":messages:",
  ["Messenger"] = ":messenger:",
  ["Microsoft Edge"] = ":microsoft_edge:",
  ["Microsoft Excel"] = ":microsoft_excel:",
  ["Microsoft Outlook"] = ":microsoft_outlook:",
  ["Microsoft PowerPoint"] = ":microsoft_power_point:",
  ["Microsoft Remote Desktop"] = ":microsoft_remote_desktop:",
  ["Microsoft Teams"] = ":microsoft_teams:",
  ["Microsoft Word"] = ":microsoft_word:",
  ["Music"] = ":music:",
  ["Neovide"] = ":neovide:",
  ["neovide"] = ":neovide:",
  ["Neovim"] = ":neovim:",
  ["neovim"] = ":neovim:",
  ["nvim"] = ":neovim:",
  ["Notion"] = ":notion:",
  ["Obsidian"] = ":obsidian:",
  ["OBS"] = ":obsstudio:",
  ["1Password"] = ":one_password:",
  ["ChatGPT"] = ":openai:",
  ["Pages"] = ":pages:",
  ["Postman"] = ":postman:",
  ["Reminders"] = ":reminders:",
  ["Safari"] = ":safari:",
  ["SF Symbols"] = ":sf_symbols:",
  ["Slack"] = ":slack:",
  ["Spotify"] = ":spotify:",
  ["Spotlight"] = ":spotlight:",
  ["Telegram"] = ":telegram:",
  ["Terminal"] = ":terminal:",
  ["Vim"] = ":vim:",
  ["VLC"] = ":vlc:",
  ["VMware Fusion"] = ":vmware_fusion:",
  ["VSCodium"] = ":vscodium:",
  ["WezTerm"] = ":wezterm:",
  ["WhatsApp"] = ":whats_app:",
  ["‎WhatsApp"] = ":whats_app:",
  ["Xcode"] = ":xcode:",
  ["zoom.us"] = ":zoom:",
}

local text <const> = {
  nerdfont = {
    plus = "",
    loading = "",
    apple = "",
    gear = "",
    cpu = "",
    clipboard = "󰅇",
    switch = {
      on = "󱨥",
      off = "󱨦",
    },
    volume = {
      _100 = "",
      _66 = "",
      _33 = "",
      _10 = "",
      _0 = "",
    },
    battery = {
      _100 = "",
      _75 = "",
      _50 = "",
      _25 = "",
      _0 = "",
      charging = "",
    },
    wifi = {
      upload = "",
      download = "",
      connected = "󰖩",
      disconnected = "󰖪",
      router = "󰑩",
    },
    media = {
      back = "",
      forward = "",
      play_pause = "󰐎",
    },
    slider = {
      knob = ""
    }
  },
}

return {
  text = text.nerdfont,
  apps = apps,
}
